export const GET_LOCATIONS_START = '@IKUBOTA:GET_LOCATIONS_START';
export const GET_LOCATIONS_SUCCES = '@IKUBOTA:GET_LOCATIONS_SUCCES';
export const GET_LOCATIONS_ERROR = '@IKUBOTA:GET_LOCATIONS_ERROR';