export const GET_LOCATIONS_START = '@IKUBOTA:GET_LOCATIONS_START';
export const GET_LOCATIONS_SUCCES = '@IKUBOTA:GET_LOCATIONS_SUCCES';
export const GET_LOCATIONS_ERROR = '@IKUBOTA:GET_LOCATIONS_ERROR';
export const GET_INTINERARIOS_START = '@IKubota:GET_INTINERARIOS_START';
export const GET_INTINERARIOS_SUCCESS = '@IKubota:GET_INTINERARIOS_SUCCESS';
export const GET_INTINERARIOS_ERROR = '@IKubota:GET_INTINERARIOS_ERROR';